version: "3.8"
services:
  mysqldb:
    container_name: user_db
    image: mysql:5.7
    restart: always
    ports:
      - 3335:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=user_db
    volumes:
      - db:/var/lib/mysql
volumes:
  db: