version: "3.8"
services:
  mysqldb:
    container_name: ${CONTAINER_NAME}
    image: mysql:5.7
    restart: always
    ports:
      - ${CONTAINER_LOCAL_PORT}:${CONTAINER_HOST_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - db:/var/lib/mysql
volumes:
  db: